parameters:
#    market.example.class: Lokal\Bundle\MarketBundle\Example

services:
#    market.example:
#        class: %market.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
