parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: lokal
    database_user: root
    database_password: null
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 256be52d3e3dd86104d3444f6bc94ec570c54682
    database_path: null
